# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 241f19e14edeccad5e3379ffb756f08a8e95472b517f387e5cf48b29bc45a41ed15cbcfc7ef2d490a6c1a6180785676df031c6af0e6b8836aeb1d058fbd96a71

test:
  secret_key_base: e38cd77674db093170e4530b7c1f490be63cc6b1cffc32a43f6445888774987cfa60f672ca49214591af47228426060e0f4675ec2b88360e60ce007d937e209c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
